#!/usr/bin/env python3
"""把固定播报语合成为 16 kHz 单声道 16bit 裸 PCM，并生成 C 头文件（离线播报用）。

为什么离线要用预合成片段：TTS 在云上，断网就哑。智能家居的固定播报
（开灯/关灯/离线提示）完全可以预先合成好烧进固件，播放时零网络依赖。

用法（在 WSL 里跑，那里有网络和 python3）：
    python3 make_voice_clips.py <输出目录> <sdkconfig路径>

产物：
    <输出目录>/<name>.pcm        16 kHz mono s16le 裸 PCM
    <输出目录>/voice_clips.h     带 C 数组 + 名字表的头文件
"""

import base64
import json
import os
import re
import struct
import subprocess
import sys
import urllib.request

HOST = "https://token-plan-cn.xiaomimimo.com/v1/chat/completions"
VOICE = "冰糖"

# 名字 -> 要说的话。挑的是智能家居离线场景里最常说的几句。
CLIPS = [
    ("light_on", "客厅灯已打开"),
    ("light_off", "客厅灯已关闭"),
    ("red_on", "红灯已打开"),
    ("blue_on", "蓝灯已打开"),
    ("offline", "网络已断开，已切换到本地控制"),
    ("ok", "好的"),
    ("unknown", "没有听懂，请再说一遍"),
    ("temp_high", "注意，芯片温度偏高"),

    # 网关（ESP32-S3）本地判出来的米家答复：这些句子由设备侧的网关生成，
    # 断网时云端 TTS 用不了，所以同样预合成。带数字的句子（亮度 / 色温）
    # 用一句通用播报——为每个取值预合成不值得占的 flash，屏上仍显示数字。
    ("lamp_on",    "台灯已打开"),
    ("lamp_off",   "台灯已关闭"),
    ("ac_on",      "空调已打开"),
    ("ac_off",     "空调已关闭"),
    ("bright_set", "台灯亮度已调好"),
    ("ct_set",     "台灯色温已调好"),
    ("no_reply",   "设备没有回应"),
    ("no_device",  "没有找到这台设备"),

    # 板载 RGB 灯（S3 上那颗 WS2812）的答复：同样由网关本地生成。
    # 闪 N 下、呼吸这类带次数的句子走 led_blink / led_breath 两句通用播报，
    # 屏上仍是精确句（"红灯闪了 3 下"）。
    ("green_on",   "绿灯已打开"),
    ("white_on",   "白灯已打开"),
    ("yellow_on",  "黄灯已打开"),
    ("rgb_on",     "RGB灯已打开"),
    ("rgb_off",    "RGB灯已关闭"),
    ("led_blink",  "灯已闪烁"),
    ("led_breath", "灯已进入呼吸模式"),
]

OUT_DIR = sys.argv[1] if len(sys.argv) > 1 else "."
SDKCONFIG = sys.argv[2] if len(sys.argv) > 2 else (
    "/mnt/c/Users/Lawson/sf32lb52_net_build/esp32s3_gateway/sdkconfig"
)


def load_key(path):
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            m = re.match(r'^CONFIG_GATEWAY_CLOUD_API_KEY="(.*)"', line.strip())
            if m and m.group(1):
                return m.group(1)
    raise SystemExit("找不到 API key: %s" % path)


def synth(text, key):
    body = json.dumps({
        "model": "mimo-v2.5-tts",
        "messages": [{"role": "assistant", "content": text}],
        "audio": {"format": "wav", "voice": VOICE},
    }).encode("utf-8")

    req = urllib.request.Request(HOST, data=body, headers={
        "Authorization": "Bearer %s" % key,
        "Content-Type": "application/json",
    })

    with urllib.request.urlopen(req, timeout=90) as resp:
        doc = json.loads(resp.read().decode("utf-8"))

    b64 = doc["choices"][0]["message"]["audio"]["data"]
    return base64.b64decode(b64)


def wav_to_pcm16k_mono(wav):
    """WAV(24k mono s16) -> 16k mono s16，与板端同一条 3:2 取平均的算法。"""
    pos = 12
    rate = channels = bits = None
    pcm = None

    while pos + 8 <= len(wav):
        cid = wav[pos:pos + 4]
        size = struct.unpack("<I", wav[pos + 4:pos + 8])[0]
        body = wav[pos + 8:pos + 8 + size]
        if cid == b"fmt ":
            channels, rate = struct.unpack("<HI", body[2:8])
            bits = struct.unpack("<H", body[14:16])[0]
        elif cid == b"data":
            pcm = body
            break
        pos += 8 + size + (size & 1)

    if pcm is None or rate != 24000 or channels != 1 or bits != 16:
        raise SystemExit("意外的 WAV 格式: rate=%s ch=%s bits=%s" % (rate, channels, bits))

    samples = struct.unpack("<%dh" % (len(pcm) // 2), pcm[: len(pcm) // 2 * 2])
    frames = len(samples)

    # 抗混叠低通（Blackman 窗 sinc，截止 7 kHz）之后再做 3:2 插值：
    # 直接丢采样会把 8 kHz 以上的分量折回可听带，听感发沙、发卡。
    import math

    cutoff = 7000.0 / rate
    taps_n = 63
    half = (taps_n - 1) / 2.0
    taps = []
    for i in range(taps_n):
        x = i - half
        if abs(x) < 1e-9:
            h = 2 * cutoff
        else:
            h = math.sin(2 * math.pi * cutoff * x) / (math.pi * x)
        w = (0.42 - 0.5 * math.cos(2 * math.pi * i / (taps_n - 1))
             + 0.08 * math.cos(4 * math.pi * i / (taps_n - 1)))
        taps.append(h * w)
    gain = sum(taps)
    taps = [t / gain for t in taps]

    filtered = [0.0] * frames
    for i in range(frames):
        acc = 0.0
        lo = i - int(half)
        for j, c in enumerate(taps):
            k = lo + j
            if 0 <= k < frames:
                acc += samples[k] * c
        filtered[i] = acc

    out_frames = (frames * 2) // 3
    out = []
    for k in range(out_frames):
        pos = k * 1.5
        i0 = int(pos)
        frac = pos - i0
        a = filtered[i0]
        b = filtered[i0 + 1] if i0 + 1 < frames else a
        v = a + (b - a) * frac
        if v > 32767:
            v = 32767
        elif v < -32768:
            v = -32768
        out.append(int(v))

    return struct.pack("<%dh" % len(out), *out)


def emit_header(clips, path):
    lines = [
        "/* Generated by make_voice_clips.py -- do not edit by hand.",
        " *",
        " * Offline announcement clips: 16 kHz mono 16-bit PCM, synthesized once",
        " * and embedded in the image so the device can speak with no network.",
        " */",
        "",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "",
        "typedef struct {",
        "    const char *name;",
        "    const unsigned char *pcm;",
        "    size_t len;",
        "} voice_clip_t;",
        "",
    ]

    for name, data in clips:
        lines.append("static const unsigned char clip_%s[] = {" % name)
        row = []
        for i, byte in enumerate(data):
            row.append("0x%02x," % byte)
            if len(row) == 16:
                lines.append("    " + "".join(row))
                row = []
        if row:
            lines.append("    " + "".join(row))
        lines.append("};")
        lines.append("")

    lines.append("static const voice_clip_t voice_clips[] = {")
    for name, data in clips:
        lines.append('    { "%s", clip_%s, sizeof(clip_%s) },' % (name, name, name))
    lines.append("};")
    lines.append("")
    lines.append("#define VOICE_CLIP_COUNT (sizeof(voice_clips) / sizeof(voice_clips[0]))")
    lines.append("")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main():
    key = load_key(SDKCONFIG)
    os.makedirs(OUT_DIR, exist_ok=True)

    out = []
    total = 0

    for name, text in CLIPS:
        wav = synth(text, key)
        pcm = wav_to_pcm16k_mono(wav)
        with open(os.path.join(OUT_DIR, name + ".pcm"), "wb") as fh:
            fh.write(pcm)
        seconds = len(pcm) / (16000 * 2)
        print("%-10s %-16s %6d bytes  %.2f s" % (name, text, len(pcm), seconds))
        out.append((name, pcm))
        total += len(pcm)

    header = os.path.join(OUT_DIR, "voice_clips.h")
    emit_header(out, header)
    print("\n合计 %d 字节（%.0f KB），头文件 %s" % (total, total / 1024, header))


if __name__ == "__main__":
    main()
